script:
  - bundle
  - bundle exec rake appraisal:install
  - bundle exec rake appraisal
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.2
  - ruby-head
  - rbx-19mode
# JRuby is taking too long at the moment :(
#  - jruby-19mode
#  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-19mode
    - rvm: rbx-19mode
notifications:
  email:
    on_success: always
    on_failure: always
